import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: 
  Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        {/* {children} in the root layout.tsx represents every 
        possible page and component that will ever be rendered in the application */}
        <ThemeProvider> {children} </ThemeProvider>
      </body>
    </html>
  );
}


// app/page.tsx     http://localhost:3000
// app/toyprob4/page.jsx    http://localhost:3000/toyprob4
